[platformio]
default_envs = esp32-s3-n16r8

[env:esp32-s3-n16r8]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
upload_port = COM18
monitor_port = COM18
monitor_speed = 921600
upload_speed = 921600
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D INA226_I2C_ADDRESS=0x40
    -D SHT31_I2C_ADDRESS=0x44
    -D INA226_SDA_PIN=4
    -D INA226_SCL_PIN=5
    -D RADXA_UART_RX_PIN=10
    -D RADXA_UART_TX_PIN=9
    -D RADXA_UART_BAUD=115200
    -D INA226_SAMPLE_INTERVAL_MS=10
    -D INA226_INTEGRATION_GAP_MS=30
    -D INA226_STATUS_INTERVAL_MS=2000
    -D SHT31_ENV_INTERVAL_MS=1000
    -D INA226_SHUNT_OHMS=0.01f
    -D INA226_CURRENT_LSB_A=0.000125f
